# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\"\xb1\x01\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1a\n\x05genre\x18\x04 \x01(\x0e\x32\x0b.Book.Genre\x12\x0c\n\x04year\x18\x05 \x01(\x05\"R\n\x05Genre\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x46ICTION\x10\x01\x12\x12\n\x0eSCIENCEFICTION\x10\x02\x12\x0e\n\nNONFICTION\x10\x03\x12\x0b\n\x07MYSTERY\x10\x04\"\xaa\x01\n\rInventoryItem\x12\x17\n\x0finventoryNumber\x18\x01 \x01(\x05\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.InventoryItem.Status\x12\x15\n\x04\x62ook\x18\x03 \x01(\x0b\x32\x05.BookH\x00\"/\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tAVAILABLE\x10\x01\x12\t\n\x05TAKEN\x10\x02\x42\x11\n\x0finventory_oneof\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t2J\n\x10InventoryService\x12\x1d\n\ncreateBook\x12\x05.Book\x1a\x08.Message\x12\x17\n\x07getBook\x12\x05.Book\x1a\x05.Bookb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=18
  _BOOK._serialized_end=195
  _BOOK_GENRE._serialized_start=113
  _BOOK_GENRE._serialized_end=195
  _INVENTORYITEM._serialized_start=198
  _INVENTORYITEM._serialized_end=368
  _INVENTORYITEM_STATUS._serialized_start=302
  _INVENTORYITEM_STATUS._serialized_end=349
  _MESSAGE._serialized_start=370
  _MESSAGE._serialized_end=396
  _INVENTORYSERVICE._serialized_start=398
  _INVENTORYSERVICE._serialized_end=472
# @@protoc_insertion_point(module_scope)
